version: "3.9"

services:
  tfgpu:
    build:
      dockerfile: ./tests/dockerfile_tf210_gpu
    volumes:
      - ./:/code/
    command: /bin/bash
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    